[package]
name = "vmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
bitflags = "1.3.2"
utils = { path = "../utils" }
x2apic = { path = "../x2apic" }
