[package]
name = "attestation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
sha2 = "0.6.0"
ed25519 = { version = "2.2.1", default-features = false}
ecdsa = "0.16.7"

# [dependencies.aes]
# optional = true
# version = "0.4.0"

# ring = { version = "0.16.20", default-features = false}
#sha2  = {version = "0.10.7"}

[dev-dependencies.simple_logger]
default-features = false
features = ["colors"]
version = "4.1.0"