[package]
name = "capa-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"

[dev-dependencies.simple_logger]
default-features = false
features = ["colors"]
version = "4.1.0"
