[package]
name = "capa-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }

[dev-dependencies.simple_logger]
default-features = false
features = ["colors"]
version = "4.1.0"
