TRANSITION=TRUE ENCLAVES=TRUE OUTER=10 INNER=5000 ./runbench
TRANSITION=TRUE SANDBOXES=TRUE OUTER=10 INNER=5000 ./runbench
TRANSITION=TRUE CARVES=TRUE OUTER=10 INNER=5000 ./runbench
# 
HWCOMM=TRUE OUTER=10 INNER=5000 ./runbench
#
CREATION=TRUE ENCLAVES=TRUE OUTER=10 INNER=1 ./runbench
CREATION=TRUE SANDBOXES=TRUE OUTER=10 INNER=1 ./runbench
CREATION=TRUE CARVES=TRUE OUTER=10 INNER=1 ./runbench
