[package]
name = "vga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.5.2"
x86_64 = "0.14.9"

[dependencies.font8x8]
version = "0.2.5"
default-features = false
features = ["unicode"]

