name: Rust

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-22.04
    env:
      RUSTFLAGS: --deny warnings
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1 # Install `just`
    - name: Setup
      run: just setup
    - name: Check
      run: just check
    - name: Test
      run: just test

  Qemu:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: mkdir -p builds/linux-x86 && cp ~/vmlinux builds/linux-x86 && cp ~/OVMF-pure-efi.fd .
      - name: Linux
        run: timeout 15m just linux
